//----- ARTICLES ----- //
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const GET_PAGINATE_ARTICLES = 'GET_PAGINATE_ARTICLES'
export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_CURRENT_ARTICLE = 'GET_CURRENT_ARTICLE'
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const UPDATE_STATUS_ARTICLE = 'UPDATE_STATUS_ARTICLE'

//----- NOTIFICATIONS ----- //

export const ERROR_GLOBAL = 'ERROR_GLOBAL'
export const SUCCESS_GLOBAL = 'SUCCESS_GLOBAL'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'


//----- USERS ----- //

export const AUTH_USERS = 'AUTH_USERS'
export const SIGN_OUT_USER = 'SIGN_OUT_USER'
export const CHANGE_EMAIL_USER = 'CHANGE_EMAIL_USER'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'

//----- SITE ----- //

export const SITE_LAYOUT = 'SITE_LAYOUT'